// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoompskrczzucsohfcyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvb21wc2tyY3p6dWNzb2hmY3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0NjMxMjIsImV4cCI6MjA4MjAzOTEyMn0.CXP5OTLpct1SjcdDvMfYHnLgN0_B1CeQ0xCqtGYHnGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const DEFAULT_FETCH_TIMEOUT_MS = 20000;

const fetchWithTimeout: typeof fetch = (input, init) => {
  const timeout = new Promise<Response>((_resolve, reject) => {
    const id = setTimeout(() => {
      clearTimeout(id);
      reject(new Error('Network request timed out'));
    }, DEFAULT_FETCH_TIMEOUT_MS);
  });

  return Promise.race([fetch(input, init), timeout]);
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: fetchWithTimeout,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
